### ISSUE TITLE
Inset label without label

### ISSUE THREAD

**Issue by juuso-vaadin** [anezthes/vaadinplus#2]
Inset label variant could be improved by allowing it to be used together with the "hide-label" theme variant.
Currently the value is not centered if no label is set.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/19607782/204739245-e4a8c611-f5ee-4efb-98e3-ae59bc298040.png">

For example Material 2 has "Filled text fields without labels" variant: https://m2.material.io/components/text-fields#filled-text-field

**Comment by anezthes** [comment]
@juuso-vaadin should be fixed now.
